Lesson2
Dbl4/shop-project pull request #2
Opened 2021-05-31 12:21 UTC by Dbl4

2021-05-31 14:57 UTC, Vokler requested changes

2021-05-31 14:57 UTC, Vokler commented on products/views.py
> +        'title':
Лучше, чтобы конструкция словаря выглядела `key: value` (не переносите каждый элемент на новую строку)

2021-06-01 06:37 UTC, Vokler approved these changes

2021-06-01 06:37 UTC, merged

2021-06-01 06:39 UTC, Dbl4 commented on products/views.py
> +        'title':
Не заметил конструкцию словаря, измененную автоформатом, сам так не делаю) Все поправил, добавил загрузку контента из cards.json в контроллер products.