Lesson3
Dbl4/shop-project pull request #3
Opened 2021-06-03 10:24 UTC by Dbl4

2021-06-03 14:55 UTC, Vokler requested changes

2021-06-03 14:55 UTC, Vokler commented on products/views.py
> +    file_path = os.path.join(MODULE_DIR, 'fixtures/goods.json')
Расширьте context, добавив туда products и categories, которые подгружаются из БД

2021-06-04 07:30 UTC, Dbl4 commented on products/views.py
> +    file_path = os.path.join(MODULE_DIR, 'fixtures/goods.json')
Сначала не так понял задание. Все теперь поправил.

2021-06-04 07:56 UTC, Vokler approved these changes

2021-06-04 07:56 UTC, merged